import { useState, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
import { TEAMS, GROUPS, FLAGS, NAME_TO_ID, GOLDEN_BOOT, ASSISTS, TEAM_STATS } from './worldCupData';

function Mark(){return <div className="mark" aria-label="World Cup 26"><span>2</span><span>6</span></div>}

function Header(){return <header className="site-header"><a className="brand dark" href="/"><Mark/><span>FIFA WORLD CUP<br/><b>26</b></span></a><nav><a href="/matches">MATCHES</a><a href="/stats">STATS</a><a href="/teams">TEAMS</a></nav><a className="header-cta" href="/matches">FIXTURES ↗</a></header>}

function TeamFlag({name}){return <span className="team-flag">{FLAGS[name]||'⚽'}</span>}

function MatchTile({match, compact=false}){const finished=match[3]!==''&&match[3]!==undefined;return <div className={'match-tile '+(compact?'compact':'')}><div className="match-meta"><span>{match[0]}</span><b>{finished?'FT':'UP NEXT'}</b></div><div className="match-row"><span><TeamFlag name={match[1]}/>{match[1]}</span><strong>{finished?match[3]:'—'}</strong></div><div className="match-row"><span><TeamFlag name={match[2]}/>{match[2]}</span><strong>{finished?match[4]:'—'}</strong></div></div>}

function MatchesPage(){const roundLabels=[['Round of 32','ROUND OF 32'],['Round of 16','ROUND OF 16'],['Quarter-final','QUARTER-FINALS'],['Semi-final','SEMI-FINALS']];const fixturesFor=round=>Object.values(TEAMS).flatMap(team=>team.path.filter(item=>item.round===round).map(item=>({team,item}))).filter(({team,item},index,array)=>array.findIndex(entry=>[entry.team.name,entry.item.opp].sort().join('|')===[team.name,item.opp].sort().join('|'))===index);return <><Header/><main className="subpage matches-page"><div className="page-hero"><p className="eyebrow">FIFA WORLD CUP 26™ · 14 JUL 2026</p><h1>THE ROAD<br/>TO <i>GLORY.</i></h1><p>All group-stage nations and a clean, current knockout view from the supplied World Cup dataset.</p></div><section className="group-section"><div className="section-title"><span>GROUP STAGE</span><p>12 GROUPS · 48 TEAMS</p></div><div className="groups-grid">{Object.entries(GROUPS).map(([letter,teams])=><article className="group-card" key={letter}><div className="group-letter">{letter}</div>{teams.map((team,i)=><a href={NAME_TO_ID[team]?`/teams/${NAME_TO_ID[team]}`:'/teams'} key={team}><b>{String(i+1).padStart(2,'0')}</b><span><TeamFlag name={team}/>{team}</span><em>{TEAMS[NAME_TO_ID[team]]?.status||'GROUP STAGE'}</em></a>)}</article>)}</div></section><section className="knockout-section"><div className="section-title"><span>KNOCKOUT STAGE</span><p>SEMIFINAL DAY</p></div><div className="bracket-scroll"><div className="bracket clean-bracket">{roundLabels.map(([round,label])=><div className="bracket-col" key={round}><h3>{label}</h3>{fixturesFor(round).map(({team,item})=><MatchTile key={`${team.id}-${item.round}-${item.opp}`} match={[item.round,team.name,item.opp,item.score,'']} compact/>)}</div>)}<div className="bracket-col final-column"><h3>FINAL</h3><MatchTile match={['SUN 19 JUL','WINNER SF 1','WINNER SF 2','','']} compact/></div></div></div></section></main></>}

function StatsPage(){const statRows=[['GOALS',GOLDEN_BOOT[0].name,GOLDEN_BOOT[0].team,GOLDEN_BOOT[0].g],['ASSISTS',ASSISTS[0].name,ASSISTS[0].team,ASSISTS[0].a],['MINUTES',GOLDEN_BOOT[1].name,GOLDEN_BOOT[1].team,GOLDEN_BOOT[1].min],['GOAL + ASSIST',GOLDEN_BOOT[2].name,GOLDEN_BOOT[2].team,GOLDEN_BOOT[2].g+GOLDEN_BOOT[2].a]];const teamRows=[['BEST ATTACK',TEAM_STATS.bestAttack[0]],['BEST DEFENCE',TEAM_STATS.bestDefense[0]],['MOST POSSESSION',TEAM_STATS.mostPossession[0]]];return <><Header/><main className="subpage stats-page"><div className="stats-intro"><p className="eyebrow">TOURNAMENT STATS · 14 JUL 2026</p><h1>THE NUMBERS<br/><i>MAKE HISTORY.</i></h1><p>World Cup-only scoring, creativity and team-performance leaders from the supplied dataset.</p></div><section className="leader-grid">{statRows.map(([metric,player,country,value],i)=><article className="leader-card" key={metric}><span className="rank">0{i+1}</span><p>{metric}</p><strong>{value}</strong><div><TeamFlag name={country}/><span>{player}<small>{country.toUpperCase()}</small></span></div></article>)}</section><section className="team-stats"><div className="section-title"><span>TEAM INTELLIGENCE</span><p>WORLD CUP ONLY</p></div><div className="stat-bars">{teamRows.map(([label,entry])=><article key={label}><b>{label}</b><h3>{entry.team}</h3><span><i style={{width:'86%'}}></i></span><small>{entry.val} · FIFA World Cup 2026</small></article>)}</div></section></main></>}

function TeamsPage(){const roster=Object.values(GROUPS).flat();return <><Header/><main className="subpage teams-page"><div className="page-hero"><p className="eyebrow">NATIONS OF THE WORLD · 48 TEAMS</p><h1>PICK YOUR<br/><i>COLOURS.</i></h1><p>Every nation in this FIFA World Cup 2026 dataset. Detailed World Cup player cards are available for featured teams.</p></div><div className="team-directory">{roster.map((name,index)=>{const id=NAME_TO_ID[name],profile=id&&TEAMS[id],code=profile?.confed||name.slice(0,3).toUpperCase(),flag=FLAGS[name]||'⚽',primary=profile?.colors.primary||['#2436b8','#e2321c','#087b54','#6017dd'][index%4],secondary=profile?.colors.accent||'#d9f009';return <a href={id?`/teams/${id}`:'/teams'} className="team-directory-card" key={name} style={{'--primary':primary,'--secondary':secondary}}><span>{flag}</span><b>{name}</b><small>{code} · {id?'TEAM PROFILE →':'WORLD CUP 26'}</small></a>})}</div></main></>}

function Landing(){return <><main className="home-landing"><header className="home-nav"><a className="brand" href="/"><Mark/><span>FIFA WORLD CUP<br/><b>26</b></span></a><nav><a href="/matches">MATCHES</a><a href="/stats">STATS</a><a href="/teams">TEAMS</a></nav></header><div className="home-red"></div><div className="home-mint"></div><div className="home-ring"></div><div className="home-copy"><p className="eyebrow">CANADA · MÉXICO · USA</p><h1>THE WORLD<br/><i>IS ON.</i></h1><p>The biggest stage in football is here. Three countries. Forty-eight nations. One beautiful game.</p><a href="#hosts">EXPLORE THE HOSTS <b>↓</b></a></div><div className="home-26"><span>2</span><span>6</span></div><img className="home-trophy" src="/fifa-world-cup-26-emblem.png" alt="FIFA World Cup 26 emblem"/><div className="home-info"><span>11 JUN — 19 JUL</span><span>104 MATCHES</span><span>16 CITIES</span></div></main><section className="home-intro"><p className="eyebrow">FOOTBALL UNITED</p><h2>ONE CUP.<br/>THREE <i>HOME</i> CROWDS.</h2><p>Scroll through the three countries sharing football's biggest stage.</p></section><section className="host-journey" id="hosts"><article className="host-chapter canada-chapter"><i className="host-motif">✦</i><p>01 — NORTH</p><h2>CANADA</h2><span>Vancouver · Toronto</span><b>BOLD<br/>OPEN<br/>WIDE</b></article><article className="host-chapter mexico-chapter"><i className="host-motif">☀</i><p>02 — HEART</p><h2>MÉXICO</h2><span>Mexico City · Guadalajara · Monterrey</span><b>VIVA<br/>EL<br/>JUEGO</b></article><article className="host-chapter usa-chapter"><i className="host-motif">★ ★ ★</i><p>03 — ENERGY</p><h2>USA</h2><span>11 host cities · Coast to coast</span><b>ALL<br/>IN</b></article></section><section className="home-outro"><p className="eyebrow">FIFA WORLD CUP 26™</p><h2>104 MATCHES.<br/><i>ONE STORY.</i></h2><a href="/matches">SEE EVERY MATCH →</a></section></>}

function App(){const path=window.location.pathname;if(path==='/matches')return <MatchesPage/>;if(path==='/stats')return <StatsPage/>;if(path==='/teams')return <TeamsPage/>;return <Landing/>}

createRoot(document.getElementById('root')).render(<App/>);
